/**
 * G-Code Commenter Extension
 *
 * Intercepts g-code generated by the svg-parser and prepends
 * an identification comment to help track processed code.
 */

import { filter, map } from 'rxjs/operators';
import type { ServicePlugin } from '@whttlr/plugin-types';

/**
 * Plugin configuration
 */
interface GCodeCommenterConfig {
  /** Comment text to prepend (default: "; Injected from G-Code Commenter Extension") */
  commentText?: string;

  /** Whether the extension is enabled (default: true) */
  enabled?: boolean;

  /** Whether to add a timestamp to the comment (default: false) */
  includeTimestamp?: boolean;

  /** Whether to add SVG filename if available (default: false) */
  includeSvgFilename?: boolean;
}

/**
 * Default configuration
 */
const DEFAULT_CONFIG: Required<GCodeCommenterConfig> = {
  commentText: '; Injected from G-Code Commenter Extension',
  enabled: true,
  includeTimestamp: false,
  includeSvgFilename: false
};

/**
 * G-Code Commenter Service Plugin
 *
 * This plugin intercepts g-code generation events from the svg-parser
 * and prepends a comment to identify the source.
 */
export const GCodeCommenterPlugin: ServicePlugin = {
  id: 'com.whttlr.gcode-commenter',
  name: 'G-Code Commenter',
  version: '1.0.0',

  /**
   * Activate the plugin
   * Sets up event listeners to intercept svg-parser g-code output
   */
  async activate(context) {
    const { events, state, logger } = context;

    logger.info('G-Code Commenter extension activated');

    // Load configuration
    const pluginState = await state.forPlugin();
    const userConfig = await pluginState.getState() as GCodeCommenterConfig || {};
    const config: Required<GCodeCommenterConfig> = { ...DEFAULT_CONFIG, ...userConfig };

    // Subscribe to g-code generation events from svg-parser
    // The svg-parser emits 'gcode:generated' events with the parsed g-code
    const subscription = events
      .on('gcode:generated')
      .pipe(
        // Only process if extension is enabled
        filter(() => config.enabled),

        // Filter to only handle events from svg-parser
        filter((event: any) => event.source === 'svg-parser'),

        // Transform the g-code by prepending the comment
        map((event: any) => {
          logger.debug('Intercepting g-code from svg-parser', {
            originalLength: event.payload?.gcode?.length || 0
          });

          const originalGCode = event.payload?.gcode || '';

          // Build the comment
          let comment = config.commentText;

          if (config.includeTimestamp) {
            const timestamp = new Date().toISOString();
            comment += `\n; Generated: ${timestamp}`;
          }

          if (config.includeSvgFilename && event.payload?.filename) {
            comment += `\n; Source: ${event.payload.filename}`;
          }

          // Prepend comment to g-code
          const modifiedGCode = `${comment}\n${originalGCode}`;

          logger.debug('G-code modified', {
            originalLength: originalGCode.length,
            modifiedLength: modifiedGCode.length,
            commentLines: comment.split('\n').length
          });

          // Emit the modified event
          return {
            ...event,
            payload: {
              ...event.payload,
              gcode: modifiedGCode,
              modified: true,
              modifiedBy: 'gcode-commenter'
            }
          };
        })
      )
      .subscribe({
        next: (modifiedEvent) => {
          // Re-emit the modified event so downstream listeners receive it
          events.emit('gcode:modified', modifiedEvent.payload);
          logger.info('G-code comment prepended successfully');
        },
        error: (error) => {
          logger.error('Error in G-Code Commenter:', error);
        }
      });

    // Store subscription for cleanup
    (context as any)._gcodeCommenterSubscription = subscription;

    // Listen for configuration changes
    const configSubscription = state
      .forPlugin()
      .subscribe((newState: GCodeCommenterConfig) => {
        if (newState) {
          Object.assign(config, newState);
          logger.info('G-Code Commenter configuration updated', config);
        }
      });

    (context as any)._gcodeCommenterConfigSubscription = configSubscription;

    logger.info('G-Code Commenter: Listening for svg-parser events');
  },

  /**
   * Deactivate the plugin
   * Cleanup subscriptions and resources
   */
  async deactivate() {
    // Clean up subscriptions
    const context = (this as any);

    if (context._gcodeCommenterSubscription) {
      context._gcodeCommenterSubscription.unsubscribe();
      delete context._gcodeCommenterSubscription;
    }

    if (context._gcodeCommenterConfigSubscription) {
      context._gcodeCommenterConfigSubscription.unsubscribe();
      delete context._gcodeCommenterConfigSubscription;
    }

    console.log('G-Code Commenter extension deactivated');
  }
};

export default GCodeCommenterPlugin;
