name: Deploy Documentation (Simple)

on:
  push:
    branches: [main]
    paths: 
      - 'docs-site/**'
      - '.github/workflows/deploy-docs-simple.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          
      - name: Install dependencies
        working-directory: ./docs-site
        run: npm install
        
      - name: Build
        working-directory: ./docs-site
        run: npm run build
        
      - name: List build output
        working-directory: ./docs-site
        run: |
          echo "Build output:"
          ls -la build/
          echo "Index file check:"
          ls -la build/index.html || echo "No index.html found"
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs-site/build
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4